[package]
name = "rust-z3-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "meeting"
path = "src/meeting.rs"

[dependencies]
anyhow = "1.0.94"
z3 = {version="0.12", features = ["static-link-z3"]}
